### ISSUE TITLE
redirects google recaptcha to duckduckgo

### ISSUE THREAD

**Issue by technout** [disorientedperson/duckduckgo-redirect#1]
https://www.google.com/recaptcha/ links to duckduckgo. This is something i don't want to happen. Is it easy to fix?

Like this one:
https://www.google.com/recaptcha/api/fallback?k=6LfOYgoTAAAAAInWDVTLSc8Yibqp-c9DaLimzNGM&stoken=h9oM_KvnFGkc1zVNsCuNl4bc_C_2llnN-Mwhq0yzWYU17Vn3f-4r2khjrvhFTlLS6mFEXw8SUKEooHR3U95OtVGZ_yyJjOu_7bvZ9hgBeo4...

Screenshot:
![recapcha](https://cloud.githubusercontent.com/assets/20970468/20284346/f85b771c-aabc-11e6-91a5-7f67821a401b.png)

**Comment by allanburleson** [comment]
Yes, it's very easy to fix. I'll probably also add a way for people to add their own URLS to unblock. You can just disable it until I fix it; sorry about that!

**Comment by allanburleson** [comment]
This is fixed in this repository now, and the update should be approved on addons.mozilla.com within the next few days. Thanks for the bug report!

**Comment by technout** [comment]
Thank you very much! Nice initiative btw!
