### ISSUE TITLE
Breaks Google Maps search

### ISSUE THREAD

**Issue by Eagle3386** [disorientedperson/duckduckgo-redirect#10]
Steps to reproduce:
1. Go to https://maps.google.com/
2. Search for some random place, e. g. `Berlin`, via upper left search input field.

Expected result:
Google Maps moves & centers at Berlin on the map, lists details at the left sidebar, etc.

Actual result:
Only a small toast notification at the bottom appears, stating: `Server error. Please try again later`

The error happens due to the extension redirecting not only Google searches, but Google Maps searches, too & that fails due to `CORS missing allow origin`:
![image](https://user-images.githubusercontent.com/5111490/163675621-600f1600-3800-4880-95f7-7ae3b93fd0c6.png)

**Comment by allanburleson** [comment]
Thanks! Fixed in [f55eacd](https://github.com/allanburleson/duckduckgo-redirect/commit/f55eacd72e3bca4691cfc0ebf1664e80983845b2).

**Comment by Eagle3386** [comment]
Fixed within a week - awesome, Allan! Thanks so much! 👏🏻👍🏻
