### ISSUE TITLE
Clicked links from within Gmail redirect to DuckDuckGo

### ISSUE THREAD

**Issue by rivkadr** [disorientedperson/duckduckgo-redirect#4]
Can you make it so that links that are clicked in emails within Gmail actually open as links instead of redirecting to DDG?

**Comment by allanburleson** [comment]
Fixed in v2.1. Thanks!

**Comment by rivkadr** [comment]
> 
> 
> Fixed in v2.1. Thanks!

Dude, you rock. Thanks!
