### ISSUE TITLE
Chromium plugin

### ISSUE THREAD

**Issue by kargaroc** [disorientedperson/duckduckgo-redirect#7]
Would it be possible to package this as a plugin for chrome-based browsers?

**Comment by allanburleson** [comment]
The necessary changes should be pretty trivial because Chrome also uses WebExtensions. I started looking into that a few months ago and immediately forgot about it. I'll try to remember, but you're welcome to do it yourself in a new branch if I never get around to it.

**Comment by allanburleson** [comment]
I just committed the changes I made earlier at 91c147d. IIRC it doesn’t work quite right but I don’t have time to test it right now.

**Comment by allanburleson** [comment]
Finally looked at it. Only required a tiny change to make it work. I will include a Chrome packaged version in next release (but I most likely won't put it on the store because I don't want to have a Google account).
